### ISSUE TITLE
paper-autocomplete searchText is overriden on input

### ISSUE THREAD

**Issue by Bartheleway** [miguelcobain/ember-paper#1043]
Hi,

I'm using the latest v1.0.0-beta21 and I have an issue with autocomplete.

Whenever I type something in the autocomplete, it doesn't show me what I type. The second character override the first one so the search is always using 1 character ...

Does anyone got that one ?

Using Ember 3.7 (and 3.6 before).

**Comment by rahsheen** [comment]
I just noticed I was having the same issue, but it was due to trying to `mut` a relationship. So instead of something like `@onSelectionChange={{action (mut this.fooBar)}}` I was doing `@onSelectionChange={{action (mut this.foo.bar)}}`.

**Comment by xtagon** [comment]
Running into this same issue, also with mut on a relationship. Is there a way to get around this?

**Comment by xtagon** [comment]
This is happening for me on beta24, but I also tried a few older versions and have the same problem. So I'm wondering if it is a problem with the Ember version instead. I'm on Ember 3.8.

I don't think it's related to onSelectionChange either though, because I tried setting that to a custom action and even when it's not changing the selection, the bug with the search field overriding is exhibited.

Any thoughts?

**Comment by xtagon** [comment]
Tried with more Ember + Ember-Paper versions. Pinning Ember-Paper to `1.0.0-beta.19` seems to fix it, but `1.0.0-beta.20` breaks.

That leads me to believe this is what broke it:

https://github.com/miguelcobain/ember-paper/commit/95033370c720244fcc0ed07a55a93bbbbd1cc0d4
