### ISSUE TITLE
Regression: paper-menu always goes down, even if it's near the bottom of the screen

### ISSUE THREAD

**Issue by Gaelan** [miguelcobain/ember-paper#1140]
On beta.23 and earlier, `paper-menu`s near the bottom of the page looked like this:
<img width="1476" alt="Screen Shot 2020-03-23 at 4 28 35 PM" src="https://user-images.githubusercontent.com/4495750/77372641-5a085580-6d23-11ea-9106-279a6ed77e44.png">

On beta.27 and later, it looked like this:
<img width="1476" alt="Screen Shot 2020-03-23 at 4 31 42 PM" src="https://user-images.githubusercontent.com/4495750/77372798-c97e4500-6d23-11ea-9098-353b2f25415f.png">

I wasn't able to test betas 24-26 due to #1119, but beta 27's menu refactor seems to be the most likely culprit anyway.

**Comment by blmundie** [comment]
The issue is caused by https://github.com/miguelcobain/ember-paper/blob/f16aea61438886671c40f70059b908d1421b3aa6/addon/components/paper-menu/component.js#L151  It was switched to use clamp from utils instead of the local clamp function https://github.com/miguelcobain/ember-paper/blob/4a825067a37d0d3358e9034319c3545a7e61890f/addon/components/paper-menu.js#L12. 

I already started splitting the function to a class so I could understand what it was doing before I discovered the issue.  I can do a separate pull request with just adding in the clamp function for position if you prefer that to splitting it to a class.
