### ISSUE TITLE
md-avatar does not seem to be working for me.

### ISSUE THREAD

**Issue by benedikt-d** [miguelcobain/ember-paper#131]
If I add the md-avatar class to an image it seems to not change the image to the avatar circle.

**Comment by miguelcobain** [comment]
Are you using `md-avatar` inside `{{#paper-item`?

**Comment by benedikt-d** [comment]
That was the problem. Missed that.

**Comment by benedikt-d** [comment]
Md-avatar seems kind of small though now.

**Comment by miguelcobain** [comment]
Different from the demo? http://miguelcobain.github.io/ember-paper/#/list-controls

Can you provide a screenshot?

**Comment by benedikt-d** [comment]
Screenshots in the post above.

I did some further digging in my code. Probably the mess up is the fault of how I set up my components. 
It is strange though that it does not work properly.

```{{#paper-content classNames="md-whiteframe-z1 content"}}
	{{#paper-list}}
		{{#each sortedConversations as |item|}}
			{{#paper-item class="md-3-line" param=item}}
				
				{{#liquid-if deleteToggle}}
					{{delete-toggle item=item deleteItem='deleteItem'}}
				{{/liquid-if}}

				{{conversations/index/conversations-list/conversations-item userName=item.contact.userName lastConversationTime=item.lastConversationTime profilePictureUrl=item.contact.profilePictureUrl id=item.id}}
				

			{{/paper-item}}
			{{paper-divider}}
		{{/each}}
	{{/paper-list}}
{{/paper-content}}````

```
{{#paper-item}}
	<img src="{{profilePictureUrl}}" alt="{{userName}}" class="md-avatar">
	<div class="md-list-item-text">
		<h3>{{userName}}</h3>
		<span class="lastConversationTime">{{ago lastConversationTime}}</span>
	</div>
	{{icon-button icon="chevron-right" size=2}}
{{/paper-item}}
```

**Comment by miguelcobain** [comment]
That is expected because the styles target the **first child** that has a class of `md-avatar`.
You really need the delete button to be the first child of paper-item?

Doesn't any of the demos here make sense for your delete button?
http://miguelcobain.github.io/ember-paper/#/list-controls

Try to make a way to not have that `{{#liquid-if deleteToggle}}` as a first child of paper-item.

**Comment by benedikt-d** [comment]
I guess it doesn't have to be the first child. Even though it would make sense to be the first child because the delete toggle would be the element that appears in front of the md-avatar element. Shouldn't the css be pointing to any md-avatar that are children of a list item. I guess this is the css that is used for angular material right?

**Comment by miguelcobain** [comment]
Yes. It's straight from there.

They must have their reasons for only targeting the first-child, I assume, maybe because of the `margin-right`.

Material design offers a spec where you can add secondary actions to a list item. If you're trying to use a different approach to an action, you're basically fighting against the design spec and consequently fighting ember-paper.
