### ISSUE TITLE
To ember-cli-materialize or to not ember-cli-materialize?

### ISSUE THREAD

**Issue by miguelcobain** [miguelcobain/ember-paper#17]
A new css framework for Material design has emerged. It's called materialize: http://materializecss.com/

Their [github repository] looks really good: https://github.com/Dogfalo/materialize
Decent amount of commits, contributers and stars.

Additionally, [ember-cli-materialize](https://github.com/sgasser/ember-cli-materialize) appeared. This addon goal is very similar to ember-paper, but using materialize CSS (which is really the hardest part).

I began wondering if it made sense to migrate all our efforts to ember-cli-materialize and materialize.
I like diversity, but I'm definitely not a fan of duplicated projects. That confuses users and it isn't efficient.

I would like to know ember-paper users thoughts on this question.

**Comment by rsaccon** [comment]
i am using for my very specific needs a mix of  materializecss and ember-paper. The problem with materializecss  is that it is like bootstrap, all done with jQuery plugins and tons of external libraries included (the good of course is the very large feature set and an impressive commit activity).  ember-cli-materialize is just a wrapper for materializecss, all the JS stuff is done by materializecss for the two components they have in the demo.  Ember paper however is very elegant and in JS things are done the ember way and no external libraries are included or required, but the feature set is a bit limited right now. What about just using the CSS straight from materializecss instead of angular-material ?. That is more or less what I am doing, and I plan to add ember-mobiletouch (hammer/fastclick based, very active development) to the mix. If there is a big enough overlap between my own requirements and the direction ember paper is going, I would love to contribute.

**Comment by miguelcobain** [comment]
So, you're basically proposing something in the middle.
Like using materialize CSS/SASS, but not the Javascript part?

Don't know how coupled these two things are, but it might be worth a try.

**Comment by rotatingJazz** [comment]
+1 for @rsaccon 's comment. Doing things the ember way is the way to go, imho.

**Comment by akhar** [comment]
+1 for @rotatingJazz 's comment.

**Comment by fouad** [comment]
[LumX](http://ui.lumapps.com/directives/dropdowns) looks like a really good option and it's written in SASS. Transitioning from their Angular directives to Ember components looks pretty straightforward.

**Comment by salzhrani** [comment]
FWIW materialize isn't the most adherent to the spec ... angular material look much better. :-1:  on materialize :+1:  on current direction which looks a lot better.

**Comment by miguelcobain** [comment]
Angular material is much more complete and closer to the spec, indeed.

Quoting from https://material.angularjs.org/
> Similar to the Polymer project's Paper elements collection, Angular Material **is supported internally at Google by the Angular.js, Material Design UX and other product teams**.

Besides this, I really like ember-paper's classes and overall architecture: Having ripple support/shadows in a mixin, extending from a subclass (BaseFocusable) to get similar behavior, etc. I feel like the designs concepts are mapped to the object model, and that's so sexy (and possibly more maintainable and performant).

Would love to see other users input on this matter. I'd love to combine efforts.

**Comment by fouad** [comment]
This is just nitpicking, but thoughts on changing prefix to `md-` like `{{md-button}} so that it's more like http://material.angularjs.org. Also it's faster to type.

**Comment by miguelcobain** [comment]
@fouad excellent suggestion.

Blockless versions were added in 07c800f756c9c0a09f8d6e7de66cfad7894223cd

**Comment by miguelcobain** [comment]
I think that a point was proven that Ember Paper has its own value and therefore should remain existing.
Closing.

**Comment by sgasser** [comment]
Materializecss looks really good and they adding very fast new elements and features. At the moment ember-cli-materialize with materializecss is much more complete then Ember Paper - for this reason I made ember-cli-materialize. If Ember Paper add more elements and features of angular material then I think it will be the main material library for Ember. And ember-cli-materialize will be only a wrapper for materializecss.

Ember Paper should absolutely remain existing.
