### ISSUE TITLE
required validation for paper-select?

### ISSUE THREAD

**Issue by jamesdixon** [miguelcobain/ember-paper#180]
@peec is there a quick way to add simple required validation for `paper-select` as there is in Angular material? I see that it extends `paper-input` and seems to be assigned classes such as `md-input-focused` and `md-input-has-value`, but it doesn't seem to allow for any sort of basic validation. It would be great to run a 'required` validation once the paper-select is dirty and no value has been selected.

**Comment by DanChadwick** [comment]
I haven't tried it, but `paper-input`'s validation has been re-done. I suspect validation will work since `paper-select` extends `paper-input`. If still interested in this feature, please test and re-open if there is an issue. Use the `master` branch. See the dummy app in `master` for examples and documentation.
