### ISSUE TITLE
Update px to em

### ISSUE THREAD

**Issue by srsgores** [miguelcobain/ember-paper#186]
One of my biggest pet peeves is ``px`` over ``em`` or ``rem``.  It prevents the design from properly scaling with other elements.  This addon uses *some* ``em``, but the rest (for example [things like this](https://github.com/miguelcobain/ember-paper/blob/master/app/styles/paper-list.scss#L112)) still need to be migrated to ``em``.

I am willing to make this change, provided it is a welcome one.

Thoughts?

**Comment by mike1o1** [comment]
Thanks for the feedback. For this project, though, we take the stylesheets
directly from Google's angular-material project. I don't see us deviating
from their stylesheets too much, unless there are Ember specific
implementations that we need to make.

**Comment by srsgores** [comment]
I see.  Perhaps I will create an issue on [angular-material](https://github.com/angular/material) in that case.  That way, you can take from them, and we can maybe kill two birds with one stone.

**Comment by srsgores** [comment]
Ok, [issue has been created](https://github.com/angular/material/issues/4974)

**Comment by srsgores** [comment]
Given the recent information, perhaps is https://github.com/miguelcobain/ember-paper/issues/187 irrelevant?

**Comment by DanChadwick** [comment]
The Angular issue was closed, but the only change was moving the breakpoints to em's. I think you had a much bigger change in mind. As far as I know, the Angular Material project implements the Material Design spec, and there seem to be a lot of px in it. Since we use the Angular stylesheets unchanged by human hands, I don't see anything that we can do about this here. Feel free to reopen to discuss further.
