### ISSUE TITLE
Enhancement idea - Paper input date 

### ISSUE THREAD

**Issue by ssirowy** [miguelcobain/ember-paper#217]
Consider allowing the `paper-input` component to bind directly on a first class Javascript date object for it's value.  Changing dates to `YYYY-MM-DD` format is slightly annoying.

**Comment by DanChadwick** [comment]
I think its probably beyond what a UI-component library should do, especially since there is not UI component that you are referring to. Also, do you use native javascript dates or, say, moment.js objects? It would be pretty easy to write a wrapper component or to override `{{paper-input}}`. I think that this would make a great addition to `ember-paper-cuts`, which is a collection of components that don't have direct Angular Material counterparts.

Let's close this for now, but feel free to re-open if you want to continue the discussion.
