### ISSUE TITLE
Textarea is not working

### ISSUE THREAD

**Issue by choallin** [miguelcobain/ember-paper#327]
I want to have a textarea within my form and put this tag in it:
`{{paper-input type="textarea" attr-name="description" attr-rows=3 attr-cols=5 label="Description" value=model.description}}`
But it is not rendered as a textarea, but instead it is a normal input field. I just upgraded to version 0.2.12.
What can I do to get a textarea here?

**Comment by miguelcobain** [comment]
@choallin can you try `{{#paper-input textarea=true`?

**Comment by choallin** [comment]
Thanks, that solved the probelm. :blush:

**Comment by choallin** [comment]
It seems that I have missed the line in the documentation where it is the way you wrote it...

**Comment by richaus** [comment]
{{#paper-input textarea=true doesn't work... it throws an error "paper-input doesn't match paper-form - 8:9" neither does {{form.input textarea=true ... it doesn't throw an error but displays as a regular input...

**Comment by panthony** [comment]
@richaus No `textarea=true` is the proper way and it works.

Your problem must come from something else in your app

**Comment by pauln** [comment]
@richaus the "paper-input doesn't match paper-form" error is because you've (at least in your comment here) opened the paper-input with a `#`, putting it into block mode - but presumably don't have a closing `{{/paper-input}}` tag.  Unless you're adding a hint (per the docs), you probably don't want to be using block mode; remove the `#` at the start of your `{{paper-input}}` tag and that error should disappear.  That said, if you're using it in a paper-form and want it to feed into the form's validation (i.e. if it's a `required` field, `form.input` is probably what you want.

Also bear in mind that a textarea paper-input looks very similar to a "normal" text input by default; you may want to set the number of rows to make it start taller; the example in the docs uses `passThru=(hash rows=5 maxRows=5)` to fix it to 5 rows tall.

**Comment by richaus** [comment]
Yea I've closed it. I just showed the starting bit of my code snippit. Although I did realize that the textarea does in fact (as you mention) look very much like the regular input. So we're good! Thanks for the help!!
