### ISSUE TITLE
Select with async support

### ISSUE THREAD

**Issue by choallin** [miguelcobain/ember-paper#333]
This is not an issue but a question. Maybe this can be used to clearify the docu...  
I want to use the select statement with async support. It is mentioned in the docu, that for this there is the on-open callback. Unfortunatly, I'm a beginner in Ember too so I don't know where to put the on-open action.  
Can I use a action method in the route? Or should I create a controller and put it there (action: on-open action)?

**Comment by DanChadwick** [comment]
`on-open` was a confusing name inherited from Angular Material, upon which the `ember-paper` styles are based. In the lastest master branch, which has not been released yet, it has been renamed `getItems`. This is a callback while returns a promise which resolves into a list of items for the select element. It is not an action.

In the released version, the `{{paper-select}}` will set the value. In the master version, it will (eventually) use the "Data Down, Actions Up" aka DDAU design philosophy. With this, instead of changing the value bound to the component, it will call an action that you bind to `onChange`, which will contain the new value. You can use that action to change route. 

With version 0.2 you would have to observe a change in value and use that to change the route. This code would most likely reside in a controller.

Please reopen if you have further questions.
