### ISSUE TITLE
{{paper-input}} is requiring onChange action

### ISSUE THREAD

**Issue by lefteyecc-pu** [miguelcobain/ember-paper#375]
Hello guys,

I'm getting the following error:

```js
Error: Assertion Failed: {{paper-input}} and {{paper-select}} require an `onChange` action.
```
Does {{paper-input}} require the onChange by default?

I see it here in {{paper-input}} paper-input.js (https://github.com/miguelcobain/ember-paper/blob/master/addon/components/paper-input.js#136) component but don't understand why that's needed:

```js
// Lifecycle hooks
  didReceiveAttrs() {
    this._super(...arguments);
    assert('{{paper-input}} and {{paper-select}} require an `onChange` action.', !!this.get('onChange'));
    this.notifyInvalid();
},
````

If it is needed and I don't need the functionality, how do I disabled onChange?

**Comment by miguelcobain** [comment]
@lefteyecc-pu if you don't have an `onChange` action you would never be notified of changes in the input.
What possible use case doesn't need `onChange`?

**Comment by lefteyecc-pu** [comment]
@miguelcobain I'm not asking why it's there. I'm asking why I need an
onChabnge action to be defined by default. I'm using the input in a form
and need to define an onChange action for each input otherwise I get an
error. Is this right? I can understand if I need to handle  custom onChange
actions but by default this shouldn't be the case?

**Comment by DanChadwick** [comment]
@lefteyecc-pu: I think the part you're missing is that `paper-input` is not (in the 1.0 branch) a one-way component. The value is read, but not updated by the component. The `onChange` event transmits the value back via the bound action. See the examples in the documentation site. Without an `onChange` action, you would have no way to get the value entered by the user. 

This is a change from the behavior in 0.2, in which all the components used two-way binding.

**Comment by lefteyecc-pu** [comment]
@DanChadwick So what you're saying is that I need to update all uses to {{paper-input}} to add an onChange helper even though the input is inside of a form? Not being a smart-ass, just asking. And if I do, how do I use {{paper-input}} with a form if the form element is handling validation and saving?

**Comment by DanChadwick** [comment]
The template examples are somewhat out-of-date. Look at the actual code. For example:
`{{paper-input label="Name" value=name onChange=(action (mut name))}}`
The demonstration app is being updated to automatically generate the code samples so that they can't be out-of-date. Thanks @joukevandermaas !!

So, yes, without `onChange`, your value will never change. This is how one-way component work. ember-paper 1.0 will use one-way components.

**Comment by miguelcobain** [comment]
@lefteyecc-pu you were using paper-input just to render inputs inside a `<form`?

How does your foram submission work? You're using the native one, using the `name` attribute?

**Comment by xomaczar** [comment]
@miguelcobain @lefteyecc-pu @DanChadwick maybe if the input is disabled/readonly we should not require onChange handler, but then again we will need to check for it all the time in didupdateattrs

**Comment by miguelcobain** [comment]
@xomaczar need a valid use case where onChange isn't needed. :/

**Comment by xomaczar** [comment]
@miguelcobain i am still on pre 1.0 version, so I don't really have this issue - but just thinking out loud - there are limited cases where I am using a readonly paper-input mainly for styling consistency.

**Comment by xomaczar** [comment]
@miguelcobain is this not a valid use case?

**Comment by miguelcobain** [comment]
This seemed a good idea, especially to help migration.

ember-power-select also asserts the presence of onChange. Maybe @cibernox can provide some input (pun unintended) here.

**Comment by cibernox** [comment]
@miguelcobain My approach was simple, I just check in the `init` hook that the value of `onChange` a function (I could be a string if you don't want to enforce closure actions, but I do).

However, I think that this could be improved because those calls to `Ember.assert` are not removed in production at the moment, and they should. I just haven't had the time to investigate how to remove it.

**Comment by miguelcobain** [comment]
@cibernox that is already the case in ember-paper master. The question is that some argue we shouldn't force onchange to be present. @xomaczar presents us a use where he wouldn't want to use an onchange function: a disabled input

**Comment by SaladFork** [comment]
Maybe it makes more sense to check for the presence of an `onChange` function at the point we'd try to call it (because the value changed), what looks to be `handleInput`? I believe this would handle the case of a disabled input while also providing some help to those trying to use it two-way.

**Comment by cibernox** [comment]
I think that EPS forces the actions to be there. 

The main thing is that i believe that this kind of assertions should be as eager and fail as soon as possible instead of wait until the action is used. If a component is disabled now but it might be enabled in the future, the action is mandatory.

In theory you could allow only the action to not be there if the `disabled` property is static (`disabled=true`), but if it might ever change `disabled=isDisabled`, there is a chance that it will be enabled and the invocation should throw. Afaik, there is no way of distinguish between `disabled=true` and `disabled=(readOnly maybeTrueButWhoKnows)`.

**Comment by DanChadwick** [comment]
Since assert is not removed by default, because extra lifecycle hooks are needed, because even the most rudimentary testing will reveal the problem, because this is a static usage problem, because we don't test for any of the other zillion usage problemsand because unlike EPS we use sendAction which protects against an undefined action, I suggest we just remove it.

**Comment by miguelcobain** [comment]
This assertion is still relavant in normal use cases. And I believe ember-cli will remove assertions in production code at some point. I'm divided. :/

**Comment by cibernox** [comment]
@miguelcobain I think that ember-cli doesn't remove it but it is possible to do it. Let me check

**Comment by DanChadwick** [comment]
assert !== undefined to allow onClose=false?

**Comment by miguelcobain** [comment]
You mean `onChange=false`?

**Comment by DanChadwick** [comment]
ember-cli-defeaturify?

**Comment by DanChadwick** [comment]
Whoops. Yes.

**Comment by cibernox** [comment]
I tried `ember-cli-defeaturify` just now but it doesn't seem to work with addons (or at least I failed miserable at making it strip an Ember.assert)

**Comment by miguelcobain** [comment]
Since it needs `ember-cli-build.js` / `Brocfile.js` configs, I assume it only works in apps.
Don't know if it should, however, strip addon code as well.

**Comment by cibernox** [comment]
I thought that it should work if you place the config in the `ember-cli-build.js` of the addon, but apparently that it's not the case.

**Comment by DanChadwick** [comment]
I can't see any harm in allowing `null` for when you really want no action, and it is supported by `sendAction` so we don't need any extra tests. Commited in f54b31a87ea047b88c82a00668573cdf8f7148e0. We can always revisit if some larger change is desired.
