### ISSUE TITLE
Color palette hue selection

### ISSUE THREAD

**Issue by nabihahossain** [miguelcobain/ember-paper#382]
How do I select a certain hue such as the "800" hue of "indigo" as my primary color? I understand you have to import your own sass file to override the default settings. but what call needs to be made?

**Comment by dustinfarris** [comment]
```sass
background-color: color($indigo, '800');
```

**Comment by miguelcobain** [comment]
@nabihahossain in material-design/ember-paper we have the concept of a primary palette rather than a single primary color.

The demo app overrides the primary color palette here: https://github.com/miguelcobain/ember-paper/blob/master/tests/dummy/app/styles/app.scss#L1

Basically you just need to specify a palette name and ember-paper will take care of it.
