### ISSUE TITLE
ember < 2.3 compatibility

### ISSUE THREAD

**Issue by blimmer** [miguelcobain/ember-paper#497]
This is reproducible 100% of the time on these versions of Ember.

Simply rendering paper-toolbar like this:

``` hbs
{{#paper-toolbar}}
{{/paper-toolbar}}
```

throws this exception:

``` bash
ncaught TypeError: Cannot read property 'getState' of null
handleKeyword @ ember.debug.js:46893keyword @ ember.debug.js:47048exports.default @ ember.debug.js:9053subexpr @ ember.debug.js:8570evaluateSubexpr @ ember.debug.js:46257evaluateNode @ ember.debug.js:46237acceptExpression @ ember.debug.js:46223acceptHash @ ember.debug.js:46209evaluateSubexpr @ ember.debug.js:46255evaluateNode @ ember.debug.js:46237acceptExpression @ ember.debug.js:46223acceptParams @ ember.debug.js:46197linkParamsAndHash @ ember.debug.js:47508inline @ ember.debug.js:47536RenderResult.populateNodes @ ember.debug.js:47959RenderResult.render @ ember.debug.js:47894render @ ember.debug.js:47704(anonymous function) @ ember.debug.js:48531renderAndCleanup @ ember.debug.js:48566Block._firstRender @ ember.debug.js:48528Block.invoke @ ember.debug.js:48506yieldKeyword @ ember.debug.js:10605handleKeyword @ ember.debug.js:46884handleRedirect @ ember.debug.js:46870inline @ ember.debug.js:47013content @ ember.debug.js:47548RenderResult.populateNodes @ ember.debug.js:47961RenderResult.render @ ember.debug.js:47894render @ ember.debug.js:47704(anonymous function) @ ember.debug.js:48531renderAndCleanup @ ember.debug.js:48566Block._firstRender @ ember.debug.js:48528Block.invoke @ ember.debug.js:48506ComponentNodeManager_render_instrument @ ember.debug.js:10889instrument @ ember.debug.js:11599ComponentNodeManager_render @ ember.debug.js:10882componentHook @ ember.debug.js:7967handleRedirect @ ember.debug.js:46859block @ ember.debug.js:46831block @ ember.debug.js:47528RenderResult.populateNodes @ ember.debug.js:47957RenderResult.render @ ember.debug.js:47894render @ ember.debug.js:47704(anonymous function) @ ember.debug.js:48531renderAndCleanup @ ember.debug.js:48566Block._firstRender @ ember.debug.js:48528Block.invoke @ ember.debug.js:48506yieldKeyword @ ember.debug.js:10605handleKeyword @ ember.debug.js:46884handleRedirect @ ember.debug.js:46870inline @ ember.debug.js:47013content @ ember.debug.js:47548RenderResult.populateNodes @ ember.debug.js:47961RenderResult.render @ ember.debug.js:47894render @ ember.debug.js:47704(anonymous function) @ ember.debug.js:48531renderAndCleanup @ ember.debug.js:48566Block._firstRender @ ember.debug.js:48528Block.invoke @ ember.debug.js:48506ViewNodeManager_render_instrument @ ember.debug.js:11150instrument @ ember.debug.js:11599ViewNodeManager_render @ ember.debug.js:11138render @ ember.debug.js:9881handleKeyword @ ember.debug.js:46923handleRedirect @ ember.debug.js:46870inline @ ember.debug.js:47013content @ ember.debug.js:47548RenderResult.populateNodes @ ember.debug.js:47961RenderResult.render @ ember.debug.js:47894render @ ember.debug.js:47704(anonymous function) @ ember.debug.js:48531renderAndCleanup @ ember.debug.js:48566Block._firstRender @ ember.debug.js:48528Block.invoke @ ember.debug.js:48506ViewNodeManager_render_instrument @ ember.debug.js:11150instrument @ ember.debug.js:11599ViewNodeManager_render @ ember.debug.js:11138renderHTMLBarsBlock @ ember.debug.js:11818renderBlock @ ember.debug.js:40798Renderer_prerenderTopLevelView @ ember.debug.js:22576Renderer_renderTopLevelView @ ember.debug.js:22585invoke @ ember.debug.js:318flush @ ember.debug.js:384flush @ ember.debug.js:185end @ ember.debug.js:563run @ ember.debug.js:685join @ ember.debug.js:705run.join @ ember.debug.js:20147(anonymous function) @ ember.debug.js:20210fire @ jquery.js:3099fireWith @ jquery.js:3211ready @ jquery.js:3417completed @ jquery.js:3433
```

Example:
https://github.com/blimmer/ember-cli-example-app-for-github/commit/19d733bacea1fb4d11c8c43c2ab23234adafd93f

**Comment by miguelcobain** [comment]
@blimmer the problem is that we're using contextual components in paper-toolbar: https://github.com/miguelcobain/ember-paper/blob/master/app/templates/components/paper-toolbar.hbs#L2

Contextual components are not available in ember < 2.3.

There is a way, though, to make this compatible with such versions.
Let me know if you're interested.

**Comment by blimmer** [comment]
@miguelcobain sure - can you point me at some docs to polyfill this feature?

**Comment by miguelcobain** [comment]
So, the problem here is that using ember < 2.3 means no contextual components.
The solution is to provide different templates, depending on the ember version the user is using.
In ember-leaflet we had this problem, and the solution is:
- create two directories for templates, one called `lt-2-3` and another called `current`: https://github.com/miguelcobain/ember-leaflet/tree/master/addon/templates
  - in the `lt-2-3` we add templates that override the current ones. Write here templates that **don't** use contextual components
- the real trick here is to override the addon's `treeForTemplates` hook like this: https://github.com/miguelcobain/ember-leaflet/blob/master/index.js#L40-L53
  - that hook merges both folders in a tree. `overwrite: true` makes sure that any template present in `lt-2-3` will overwrite the template present in `current`
- While you're at it, it would be nice to move all the templates from the `app` to `addon` directory. This mean that you would have to explicitly import the desired templates from the component's js, example: https://github.com/miguelcobain/ember-leaflet/blob/master/addon/components/div-overlay-layer.js#L2

This shouldn't be too hard. I've noticed that ember-power-select and ember-basic-dropdown are **2.3.1+ only** compatible.
It means that you wouldn't be able to use paper-menu, paper-select and paper-autocomplete (and in the future paper-chips) with anything below 2.3.

I'm not sure if this effort of compatibility is worth it. I'm more inclined to drop support for ember 2.3 and above, like ember-power-select does.

Suggestions welcome.

**Comment by joukevandermaas** [comment]
I think addons should support basically the lowest supported ember LTS version and up. So for now, that's 2.4 and up. After 2.10, that's 2.8 and up.

Supporting below that is great if possible, but IMO it's not worth the burden. You can always use an older ember paper version if you're stuck on an older ember version.

**Comment by blimmer** [comment]
Thanks for the info @miguelcobain - if it was as simple as including a polyfill, I think it'd be worth doing, however this seems like quite a bit of work to get this working.

I agree with @joukevandermaas - I also just opened #550 to make note of this in the readme.
