### ISSUE TITLE
Sidebar behavior

### ISSUE THREAD

**Issue by alexlafroscia** [miguelcobain/ember-paper#52]
Is the behavior of the side bar intentional?  It differs substantially from the way that it's handled on the Google Material Design site, Materialize, and any of the Material Design apps I've seen that have come from Google themselves.

**Ember Paper's Behavior**

![ember-paper](https://cloud.githubusercontent.com/assets/1645881/6455806/3d1cc580-c127-11e4-9b24-93400148de3d.gif)

**Google's Example**

![google-example](https://cloud.githubusercontent.com/assets/1645881/6455810/447e5f32-c127-11e4-97da-48370a664a33.gif)

Was there a particular reason that Ember Paper handles the behavior differently?

**Comment by miguelcobain** [comment]
Sidenav has two distinct behaviors:
 - lock open - when the viewport is big enough (currently done through css media queries) the sidenav locks open, filling a space on its own and doesn't overlay the content. Also, the sidenav toggle disappears. This seems to be the case on the first gif.
 - open/close - when the viewport is small enough (currently done through css media queries) the sidenav enters the normal open/close state, overlaying the content and showing a backdrop.

Looks like you're comparing *Ember paper's lock open* vs *Google's open/close state*. The first gif is changing between 'locked open' mode and 'open/close mode', probably because you're change viewport size. The second gif is always in the same mode, but changing between open or closed state.
If you compare both "modes", they should be similar.

One difference I noticed is the backdrop *out animation* which ember-paper doesn't have yet.

**Comment by miguelcobain** [comment]
Opened #53 for the backdrop issue.
Please let me know if you find any issues.

**Comment by alexlafroscia** [comment]
Oh, I see. I didn't realize that the behavior was different there.  Thanks for clearing that up for me!

**Comment by miguelcobain** [comment]
No problem. Adding this info to the docs may be useful for someone else.
