### ISSUE TITLE
Backdrop problems back again.

### ISSUE THREAD

**Issue by v3ss0n** [miguelcobain/ember-paper#635]
Since version 1.0.14 
Backdrop getting stucked randomly when paper-sidenav is opened repeatedly.

**Comment by miguelcobain** [comment]
@v3ss0n can you give an example and instructions to reproduce that problem?
Is it happening on the demo app?

**Comment by v3ss0n** [comment]
i will find a way to reproduce it. right now its all fine again.

**Comment by joukevandermaas** [comment]
We have this issue too on the beta-2 release. I managed to track it down to this line:

https://github.com/peec/ember-css-transitions/blob/acb057402f6a2f49f2e0e687f3053b16d2ea00c7/addon/mixins/transition-mixin.js#L214

Apparently sometimes the backdrop clone gets replaced by a *new* clone, a new element with the same ID. At that point `this.clone` still exists (not `null` or `undefined`), but does not actually point to an element that is in the DOM, and so the remove does nothing.

I don't really understand why this happens, and I don't have the time to look into it further at the moment, but this is causing our tests to fail because the scope of integration tests (`this.$`) keeps getting reset to the backdrop instead of the test container. This happens because sometimes the element is only cleaned up after the test has already finished. Also see this line for why/how the context gets set: https://github.com/emberjs/ember-test-helpers/blob/356dde46f6e71786b67114c2a5f300f9ed5aa25d/lib/ember-test-helpers/test-module-for-component.js#L253).

I know it's not a lot of information, but the TLDR is that this bug still exists :smile:

**Comment by panthony** [comment]
Could it be the same issue as #925?
