### ISSUE TITLE
textarea doesn't scroll

### ISSUE THREAD

**Issue by wooandoo** [miguelcobain/ember-paper#650]
Hi,

A textarea doesn't scroll because the CSS is setted as:

```
md-input-container textarea {
  overflow: hidden;
}
```

You can test it in:
http://miguelcobain.github.io/ember-paper/release-1/#/components/input

This can be resolved with:

```
md-input-container textarea {
  overflow: auto;
}
```

I don't know why the CSS is like that.
Is it a bug?

Have you an idea?

Frédéric

**Comment by miguelcobain** [comment]
@wooandoo does this happen on angular material? (We borrow our styles from there)

**Comment by wooandoo** [comment]
No, it's my fault: I setted the rows length. ;-)

So, with no rows defined, the textarea resizes itself like the angular version.

But when the rows is defined, we loose the scrollbar. So is it useful to have this options?

Thanks for your fast response.


Frédéric

**Comment by panthony** [comment]
For people encountering this issue you can just add this in your app scss:

```scss
.md-input {
  &.md-textarea-scrollable {
    overflow-y: auto;
  }
}
```

The `md-textarea-scrollable` is automatically appended on textarea with overflowing content.

Not sure  why it is not part of the default scss of angular though.

IMO it's important from a user point of view to have a scrollbar on textarea with overflowing content otherwise you might not see that there is more content and navigating using keyboard is tedious.
