### ISSUE TITLE
paper-button with href attribute is not generating an <a> element

### ISSUE THREAD

**Issue by arlofeirman** [miguelcobain/ember-paper#748]
Hello,

I just upgraded to paper 1.0 and am using buttons with an `href` attribute.

Code for the button:
```
{{#paper-button target="_blank" href=conversation.engineer.website}}View their website{{/paper-button}}
```
The first time I navigate to the route that this template is rendered on, a button element is generated:

```
<button target="_blank" type="button" tabindex="0" id="ember1925" 
class="md-default-theme md-button md-raised ember-view" href="https://keep.google.com/">  
  View their website
<div class="md-ripple-container"></div></button>
```

If I go to another route and back again an`<a>` tag is generated like expected:

```
<a target="_blank" href="https://keep.google.com/" tabindex="0" id="ember2428" 
class="md-default-theme md-button md-raised ember-view md-ink-ripple">  
  View their website
<div class="md-ripple-container"></div></a>
```

changing the button to:

```
{{#paper-button target="_blank" href=conversation.engineer}}View their website{{/paper-button}}
```

will generate an `<a>` tag like expected. I've defined a has many, belongs to relationship between `engineer` and `conversation` in my model files.

**Comment by miguelcobain** [comment]
The problem is that at the time of rendering `conversation.engineer.website` is undefined.
We need to know if we're going to render an `<a` or `<button` at the time of rendering. We can't change the tagName of a component after render.

Can you resolve `conversation.engineer.website` before rendering, possibly in the model hook?
Or maybe wrap the `{{#paper-button` in a `{{#if conversation.engineer.website}}`?

**Comment by arlofeirman** [comment]
Thanks Miguel. 
Wrapping the button in if helper did the trick.

```
{{#if conversation.engineer.website}}
  {{#paper-button target="_blank" href=conversation.engineer.website}}View their website{{/paper-button}}
{{/if}}
```
