### ISSUE TITLE
paper-tabs: ink bar display issue when displayed within a modal

### ISSUE THREAD

**Issue by panthony** [miguelcobain/ember-paper#771]
On master, If i do something like:

```hbs
  {{#paper-dialog class="flex-50" onClose=null clickOutsideToClose=true}}
    {{#paper-dialog-content}}
      {{#paper-tabs
        center=center
        stretch=stretch
        borderBottom=borderBottom
        selected=selectedBasicTab
        onChange=(action (mut selectedBasicTab)) as |tabs|}}
        {{#tabs.tab}}
          Page One
        {{/tabs.tab}}
        {{#tabs.tab}}
          Page Two
        {{/tabs.tab}}
      {{/paper-tabs}}

      {{#liquid-bind (hash tab=selectedBasicTab) class="md-padding" as |current|}}
        <h1 class="md-display-2">Tab {{current.tab}}</h1>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit.
          Nulla venenatis ante augue. Phasellus volutpat neque ac dui mattis
          vulputate. Etiam consequat aliquam cursus. In sodales pretium ultrices.
          Maecenas lectus est, sollicitudin consectetur felis nec, feugiat ultricies mi.
        </p>
      {{/liquid-bind}}
    {{/paper-dialog-content}}
  {{/paper-dialog}}
```

it will render like this:
![capture d ecran 2017-08-04 a 17 17 35](https://user-images.githubusercontent.com/230462/28975272-bc730e6c-7939-11e7-94c1-92059043addb.png)

Any interaction with the tabs will fix the issue.

**Comment by panthony** [comment]
Ex with `stretched=true`:

First render:
![capture d ecran 2017-08-04 a 17 25 16](https://user-images.githubusercontent.com/230462/28975355-fd40de1a-7939-11e7-8e0a-7f44cc92573d.png)


After an interaction:
![capture d ecran 2017-08-04 a 17 25 25](https://user-images.githubusercontent.com/230462/28975356-fd461286-7939-11e7-87df-1e33b3f62506.png)

**Comment by kbullaughey** [comment]
When the menu is on a sidenav the ink bar sizing can get messed up, perhaps because the size is measured while it's sliding out? 

![tiny-ink](https://user-images.githubusercontent.com/613650/29845563-530b6972-8ce1-11e7-9912-03c2e7d56be6.jpeg)

I have only produced this problem on Safari (both iOS and desktop), not Chrome (desktop).

**Comment by kbullaughey** [comment]
I was able to hack around this by adding a delayed call to `updateCanvasWidth()`: 

    import PaperTabsComponent from 'ember-paper/components/paper-tabs';
    import Ember from 'ember';
    
    export default function() {
      PaperTabsComponent.reopen({
        delayedUpdate: Ember.on('didRender', function() {
          Ember.run.later(this, function() {
            if (this.get('isDestroyed')) {
              return;
            }
            this.updateCanvasWidth();
          }, 200);
        }),
      });
    }

This happens to work, but it's ugly because you can momentarily see the incorrect bar ink. 

The underlying problem is that when `updateCanvasWidth` is normally called (during `didRender`), it gets the incorrect quantity:

    this.element.querySelector('md-pagination-wrapper').offsetWidth

I still don't understand why Chome gives the correct measurement and Safar doesn't.

**Comment by miguelcobain** [comment]
@kbullaughey can you try master version and report if that issue happens?

**Comment by kbullaughey** [comment]
@miguelcobain this was on master at a558e79638 which is still the current head.

**Comment by kbullaughey** [comment]
In my particular layout, the ink bar is so small because the full width of the `md-pagination-wrapper` is measured too large. My earlier thought about it having to do with it sliding out doesn't seem consistent with that.
