### ISSUE TITLE
paper-chips funky behavior

### ISSUE THREAD

**Issue by shoxter** [miguelcobain/ember-paper#798]
I have a paper-chips component with `options` and `requireMatch=true`.

When using the numpad to enter search text numbers, it immediately selects options that are in in the search results and closes the dropdown.

I've verified that if I search with the normal number keys, above the letters on the keyboard, it works as expected.

Has anyone else experienced this?

**Comment by pauln** [comment]
This has been fixed in a recent beta - `v1.0.0-beta.7` no longer exhibits this strange behaviour.  However, it's no longer clearing the autocomplete trigger (or rather, the autocomplete is reverting to a cached value) - so whatever you typed is still there.  I've raised #932 for that issue; this one should be safe to close now.
