### ISSUE TITLE
Npm Installating issues

### ISSUE THREAD

**Issue by betocantu93** [miguelcobain/ember-paper#845]
Hello, I have a dumb question (maybe), but also have like two hours with this issue. 

I've used ember-paper in other laptops/repos before, so I don't know why this time is not working.

When I list ember-paper as a dependency and make
$ npm install

Error 128 
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b v1.1.4 git://github.com/angular/material.git /home/betocantu93/.npm/_cacache/tmp/git-clone-1df961a6
npm ERR! /home/betocantu93/.npm/_cacache/tmp/git-clone-1df961a6/.git: Permission denied

I have tried to install my dependencies without listing as a dependency ember-paper, and they work fine, like for example ember-moment, which gets installed without issues, my thought are that maybe **v1.1.4 git://github.com/angular** has something to do with the issue.

Context: 

**OS**
Ubuntu 16.04
**npm -v:**
5.4.2

Thanks in advance, will post any news.
**node -v:** 
8.7.0

**Comment by mikeu** [comment]
@betocantu93 It looks to me as if the important part of the error message is actually the final line,
```
/home/betocantu93/.npm/_cacache/tmp/git-clone-1df961a6/.git: Permission denied
```
in particular the **`Permission denied`** error to a temp directory on your local system. The `git clone` command is failing because it cannot create a local directory to hold the angular repo. My guess is that at some time in the past you might have npm installed something to your home directory using `sudo`, but it is hard to say for sure without access to the file system and its history.

Here are some posts that address permissions issues in your local npm directory, https://stackoverflow.com/questions/16151018/npm-throws-error-without-sudo, and some ways to check the current owner of your files and directories if you want to investigate more, https://askubuntu.com/questions/175054/how-to-find-owner-and-group-of-a-directory.

**Comment by betocantu93** [comment]
@mikeu Thanks for the references, I finally got it working, and yes, it had something to do with Linux permissions, so I chmod the working directory, also reinstalled node with nvm, I'm not quite sure which one made this work though.

To be honest, it was a pain, because it's an ember-engines project with 3 engines, each as stand alone addon, so lots of npm links and installs... it made me wonder if I should go to in-repo-engines...
