### ISSUE TITLE
paper toast not show at the bottom of the screen

### ISSUE THREAD

**Issue by beastmst** [miguelcobain/ember-paper#902]
how can i setup the paper-toaster (currently parent=#body)  so when toast fire, it always show on the bottom left of the browser?  currently, it shows on the 1st page lower bottom of the browser..  even when the whole webpage is about 3 screen length.. so, how can i make it to show on the current view port bottom left corner?

thanks

**Comment by beastmst** [comment]
found a solution
https://stackoverflow.com/questions/37235457/toast-positioning-in-angular-material-page

**Comment by chadian** [comment]
Even though this was closed I wanted to leave a few reference points.
It looks like this an issue with the toasts from the underlying material package:
https://github.com/angular/material/issues/1106

Also, on the ember-paper demo site the toasts work because there's a `.site-nav-container` which is displayed absolutely but with top, right, bottom, left set to 0 so that it covers the the screen. Its parent (the root ember view under body) has `display: flex` and `flex: 1`. This keeps the "viewing container" maximized.

With the `display: flex` of `.site-nav-container` its children `md-sidenav` and `#main` end up being what you're actually scrolling.

To reproduce the two issues that people may face:
1. The toast is bound to the width/height 100% of the container but doesn't stick when scrolled.
	1. Remove `position: absolute` from `.site-nav-container`
	2. Set `display: block` on root ember view (`body > .ember-view`)
2. The toast is found at the bottom of all scrollable content
	1. Remove the same as in 1.
	2. Set `height: auto` and `max-height: unset` on the body.

This is all to say that the documentation site is setup in a way that toasts might not work out of the box.

To avoid the issues you can:
1. replicate a sort of "viewing area" that is 100% width and height via flex and/or absolute positioning like the ember-paper documentation site
2. Apply the `position: fixed` to `md-toast` like mentioned above.

We went with 2. since we don't have other fixed elements and it doesn't appear to collide with any other styles at this time. This seemed simpler than setting up a special scrolling container.
