### ISSUE TITLE
"Uncaught Error: infinite rendering invalidation detected" when using paper-tabs

### ISSUE THREAD

**Issue by atachev** [miguelcobain/ember-paper#990]
<h2>Steps</h2>

- Open dev tools(Or simply do the second step without opening with the dev tools)
- Shrink the screen horizontally under 400px
- The `<body>` should be blank now

and the exception is:
<pre>
Uncaught Error: infinite rendering invalidation detected
    at Array.loopEnd (ember-glimmer.js:4193)
    at Backburner._trigger (backburner.js:876)
    at Backburner._end (backburner.js:784)
    at Backburner.end (backburner.js:514)
    at Backburner._run (backburner.js:817)
    at Backburner._join (backburner.js:793)
    at Backburner.join (backburner.js:568)
    at Array.loopEnd (ember-glimmer.js:4196)
    at Backburner._trigger (backburner.js:876)
    at Backburner._end (backburner.js:784)
</pre>

<h2>Example</h2>
You can try it here:
<br>
<a href="https://miguelcobain.github.io/ember-paper/#/components/tabs">
https://miguelcobain.github.io/ember-paper/#/components/tabs
</a>

<h2>Note</h2>
In my current case I have 2 {{paper-tabs}} components in different pages.
<br>In the first page the tabs are into {{paper-sidenav}} which is wrapped in {{paper-card}}. Here the sidenav is toggle-able I cannot reproduce this bug even when the {{paper-sidenav}} is open. In the second page the tabs are directly added to {{paper-card}} and here the problem is reproducible.

**Comment by panthony** [comment]
After I upgraded to the latest ember-paper, all my tests using tabs where failing due to `Uncaught Error: infinite rendering invalidation detected` where the real error underneath is the following:

```
  updateDimensions() {
    let canvasWidth = this.element.querySelector('md-tabs-canvas').offsetWidth;
    let wrapperWidth = this.element.querySelector('md-pagination-wrapper').offsetWidth;
    // ....
   }
```

That may be called whereas `this.element` is `null`.

![capture d ecran 2018-12-27 a 14 53 30](https://user-images.githubusercontent.com/230462/50482511-3acb2d00-09e7-11e9-8805-857e75b48f43.png)

When `this.element` is `null` the ` isDestroying` flags is sets to `true`.
